/* AUTO-GENERATED by scripts/sync-zxing-wasm.mjs — do not edit. */
export const ZXING_WASM_PACKAGE_VERSION = "3.1.1" as const;
export const ZXING_WASM_SHA256 = "6a858c01e076bab3a1bd413e4f2cf5e5e45f819a0d9441d83c66993bc48ed38f" as const;
export const ZXING_WASM_BYTES = 1065634 as const;
export const ZXING_WASM_PUBLIC_PATH = "/wasm/zxing_reader.wasm" as const;
export const ZXING_WASM_URL = "/wasm/zxing_reader.wasm?v=6a858c01e076" as const;
export const REACT_ZXING_VERSION = "3.0.0" as const;
export const BARCODE_DETECTOR_VERSION = "3.2.1" as const;
